/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorityRouteImport } from './routes/authority'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as AuthorityIndexRouteImport } from './routes/authority.index'
import { Route as AuthorityCasesRouteImport } from './routes/authority.cases'
import { Route as AuthorityClusterIdRouteImport } from './routes/authority.cluster.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityRoute = AuthorityRouteImport.update({
  id: '/authority',
  path: '/authority',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityIndexRoute = AuthorityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityCasesRoute = AuthorityCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AuthorityRoute,
} as any)
const AuthorityClusterIdRoute = AuthorityClusterIdRouteImport.update({
  id: '/cluster/$id',
  path: '/cluster/$id',
  getParentRoute: () => AuthorityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/driver': typeof DriverRoute
  '/authority/cases': typeof AuthorityCasesRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/cluster/$id': typeof AuthorityClusterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/driver': typeof DriverRoute
  '/authority/cases': typeof AuthorityCasesRoute
  '/authority': typeof AuthorityIndexRoute
  '/authority/cluster/$id': typeof AuthorityClusterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authority': typeof AuthorityRouteWithChildren
  '/driver': typeof DriverRoute
  '/authority/cases': typeof AuthorityCasesRoute
  '/authority/': typeof AuthorityIndexRoute
  '/authority/cluster/$id': typeof AuthorityClusterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authority'
    | '/driver'
    | '/authority/cases'
    | '/authority/'
    | '/authority/cluster/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/driver'
    | '/authority/cases'
    | '/authority'
    | '/authority/cluster/$id'
  id:
    | '__root__'
    | '/'
    | '/authority'
    | '/driver'
    | '/authority/cases'
    | '/authority/'
    | '/authority/cluster/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorityRoute: typeof AuthorityRouteWithChildren
  DriverRoute: typeof DriverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority': {
      id: '/authority'
      path: '/authority'
      fullPath: '/authority'
      preLoaderRoute: typeof AuthorityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority/': {
      id: '/authority/'
      path: '/'
      fullPath: '/authority/'
      preLoaderRoute: typeof AuthorityIndexRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/cases': {
      id: '/authority/cases'
      path: '/cases'
      fullPath: '/authority/cases'
      preLoaderRoute: typeof AuthorityCasesRouteImport
      parentRoute: typeof AuthorityRoute
    }
    '/authority/cluster/$id': {
      id: '/authority/cluster/$id'
      path: '/cluster/$id'
      fullPath: '/authority/cluster/$id'
      preLoaderRoute: typeof AuthorityClusterIdRouteImport
      parentRoute: typeof AuthorityRoute
    }
  }
}

interface AuthorityRouteChildren {
  AuthorityCasesRoute: typeof AuthorityCasesRoute
  AuthorityIndexRoute: typeof AuthorityIndexRoute
  AuthorityClusterIdRoute: typeof AuthorityClusterIdRoute
}

const AuthorityRouteChildren: AuthorityRouteChildren = {
  AuthorityCasesRoute: AuthorityCasesRoute,
  AuthorityIndexRoute: AuthorityIndexRoute,
  AuthorityClusterIdRoute: AuthorityClusterIdRoute,
}

const AuthorityRouteWithChildren = AuthorityRoute._addFileChildren(
  AuthorityRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorityRoute: AuthorityRouteWithChildren,
  DriverRoute: DriverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
